### ISSUE TITLE
Exception: Lock "tag_MemcachedLock" has lost: CONNECTION DATA EXISTS

### ISSUE THREAD

**Issue by tlq0101** [cheprasov/php-memcached-lock#12]
Good day, i run my script on Debian 9, php7.0 and sometimes it throws this:
PHP Fatal error:  Uncaught MemcachedLock\Exception\LostLockException: Lock "tag_MemcachedLock" has lost: CONNECTION DATA EXISTS in /composer/vendor/cheprasov/php-memcached-lock/src/MemcachedLock/MemcachedLock.php:352
Stack trace:
#0 /composer/vendor/cheprasov/php-memcached-lock/src/MemcachedLock/MemcachedLock.php(119): MemcachedLock\MemcachedLock->release()
#1 /composer/vendor/cheprasov/php-memcached-tags/src/MemcachedTags/MemcachedTags.php(321): MemcachedLock\MemcachedLock->__destruct()
#2 /go.php(111): MemcachedTags\MemcachedTags->deleteKeysByTags(NULL)
#3 {main}
  thrown in /composer/vendor/cheprasov/php-memcached-lock/src/MemcachedLock/MemcachedLock.php on line 352

Please tell me if any way exist to solve this...

**Comment by cheprasov** [comment]
HI @tlq0101 
By the trace, It looks like you have an error with arguments for method `MemcachedTags->deleteKeysByTags(...)`
The first argument should me an array of strings (tags), but null is provided.
Please, see description of the method here https://github.com/cheprasov/php-memcached-tags#int-memcachedtags--deletekeysbytags--string-tags--int-compilation--memcachedtagscompilation_all-

**Comment by tlq0101** [comment]
Alexander, thank you for fast reply. I checked twice, it is strange why trace shows that null is provided, now i made array and provided it to MemcachedTags->deleteKeysByTags(...) and before it i used var_dump() of this array to debug. Now there is 100% not null, but error still happens, so the code that brings error is executed in foreach(), sometimes all iterations are go well, without error, and sometimes it throws error on some of iterations ;(... All configs(php,memcached) are from the box. The trace now is:

var_dump of array provided to MemcachedTags->deleteKeysByTags(...):

array(5) {
  [0]=>
  string(7) "Country"
  [1]=>
  string(10) "District:1"
  [2]=>
  string(9) "Region:24"
  [3]=>
  string(7) "City:53"
  [4]=>
  string(9) "User:3994"
}

PHP Fatal error:  Uncaught MemcachedLock\Exception\LostLockException: Lock "tag_MemcachedLock" has lost: CONNECTION DATA EXISTS in /composer/vendor/cheprasov/php-memcached-lock/src/MemcachedLock/MemcachedLock.php:352
Stack trace:
#0 /composer/vendor/cheprasov/php-memcached-lock/src/MemcachedLock/MemcachedLock.php(119): MemcachedLock\MemcachedLock->release()
#1 /composer/vendor/cheprasov/php-memcached-tags/src/MemcachedTags/MemcachedTags.php(321): MemcachedLock\MemcachedLock->__destruct()
#2 /go.php(111): MemcachedTags\MemcachedTags->deleteKeysByTags(Array)
#3 {main}
  thrown in /composer/vendor/cheprasov/php-memcached-lock/src/MemcachedLock/MemcachedLock.php on line 352

**Comment by cheprasov** [comment]
Hi @tlq0101 
The error is thrown because when it tries to release the lock, the lock is already expired. It is not an error of MemcachedLock library, it is correct behaviour for MemcachedLock library.
Also library MemcachedTags uses the lock library for control keys, but it looks like method `MemcachedTags::deleteKeysByTags()` spend more then 2 seconds delete keys by tags.

Could you please measure it something like it:
```php
$time_beg = microtime(true);
try {
    MemcachedTags->deleteKeysByTags($tags);
} catch (Exception $e) {
}
echo 'TIME ', microtime(true) - $time_beg, PHP_EOL;
```
Also, do you know how many keys it should delete by tags?

If it is a problem with spending much time for deleting keys, I will update the library and will fix the problem.

**Comment by tlq0101** [comment]
Thank you, Alexander, i made tests and the result is:

**First** iteration took about 33 seconds and var_dump(MemcachedTags->deleteKeysByTags($tags)) did not return any count of deleted keys:
TIME 33.596949100494
**Second** iteration gives:
var_dump(MemcachedTags->deleteKeysByTags($tags)): int(12)
TIME 0.12898588180542
**Third**: 
var_dump(MemcachedTags->deleteKeysByTags($tags)): int(0)
TIME 0.057614088058472
**Fourth** iteration also var_dump(MemcachedTags->deleteKeysByTags($tags)) gas no output, and time was 16 seconds:
TIME 16.201498985291
**Fifth**:
var_dump(MemcachedTags->deleteKeysByTags($tags)): int(0)
TIME 0.0008540153503418
~**Twenty fifth** also var_dump(MemcachedTags->deleteKeysByTags($tags)) no output and time is about 15 seconds:
TIME 15.686886072159
~**Twenty sixth**:
int(0)
TIME 0.00080704689025879

As you said, seems when there is not so much keys to delete (the output of var_dump(MemcachedTags->deleteKeysByTags($tags)) shows 9-15 keys) and the time is about 1 second, but when there is a lot of keys to delete time increase and i got those errors.
Alexander, thank you very much for help and fast reply. so seems my app architechture is bad in caching strategy, because of much keys under one tag? 
Also maybe the problem is that i try to delete keys that stored under all those tags, for example: i store key "key1" under tags "Country", "City:2", "Region:1" and trying to delete this key by all tags at the same time MemcachedTags->deleteKeysByTags(['Country','City:2','Region:1'])?
Thank you.

**Comment by cheprasov** [comment]
Hi @tlq0101 
I made some benchmarks, and found that the memcachedTags library works well for 5000 keys and several tags. I checked the library's code, and it is not a good solutions if you have a lot of keys. 
Please, note, the memcached is not consistent storage and mamcachedTags was created for some simple things.

> **First** iteration took about 33 seconds and var_dump(MemcachedTags->deleteKeysByTags($tags)) did not return any count of deleted keys:
TIME 33.596949100494

It looks like you have really large count of keys or tags. 
I think, it is better not to use memcachedTags here, I think, it is better to try Redis.

I created the library for invalidate cache for html pages, like:
`MemcachedTags->deleteKeysByTags(['page:news','page:user']);`

Also, but of you want to still use the library, it is better to remove of using memcachedLock in the code, or increase locktimers

**Comment by tlq0101** [comment]
Thank you for your answer, Alexander @cheprasov, apriciate it. I fully understand the situation now and will follow your advice to switch on Redis, will try to find solution how to implement tags on Redis :). Thank you so much!
